version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    assignees:
      - flavianmissi
    groups:
      openshift-dependencies:
        patterns:
          - "github.com/openshift/*"
        exclude-patterns:
          - "github.com/openshift/build-machinery-go"
      k8s-dependencies:
        patterns:
          - "k8s.io/*"
