
# Force dep to vendor the code generators, which aren't imported just used at dev time.
# Picking a subpackage with Go code won't be necessary once https://github.com/golang/dep/pull/1545 is merged.
required = [
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/conversion-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/gengo/args",
  "github.com/openshift/library-go/cmd/crd-schema-gen",
  "golang.org/x/net/http/httpproxy"
]

[[override]]
  name = "k8s.io/code-generator"
  source = "https://github.com/openshift/kubernetes-code-generator.git"
  branch = "origin-4.2-kubernetes-1.14.0"

[[override]]
  name = "k8s.io/api"
  source = "https://github.com/openshift/kubernetes-api.git"
  branch = "origin-4.2-kubernetes-1.14.0"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  source = "https://github.com/openshift/kubernetes-apiextensions-apiserver.git"
  branch = "origin-4.2-kubernetes-1.14.0"

[[override]]
  name = "k8s.io/apimachinery"
  source = "https://github.com/openshift/kubernetes-apimachinery.git"
  branch = "origin-4.2-kubernetes-1.14.0"

[[override]]
  name = "k8s.io/client-go"
  source = "https://github.com/openshift/kubernetes-client-go.git"
  branch = "origin-4.2-kubernetes-1.14.0"

[[override]]
  name = "sigs.k8s.io/controller-tools"
  source = "https://github.com/openshift/kubernetes-sigs-controller-tools.git"
  branch = "origin-4.1-kubernetes-1.13.4"

[[override]]
  name = "github.com/openshift/client-go"
  branch = "master"

[[override]]
  name = "github.com/openshift/api"
  branch = "master"

[[override]]
  name = "github.com/openshift/library-go"
  branch = "master"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.19.47"

[[constraint]]
  branch = "master"
  name = "github.com/gophercloud/gophercloud"

[[constraint]]
  branch = "master"
  name = "github.com/gophercloud/utils"

[[constraint]]
  name = "github.com/Azure/azure-sdk-for-go"
  version = "30.0.0"
