---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: configs.imageregistry.operator.openshift.io
spec:
  group: imageregistry.operator.openshift.io
  scope: Cluster
  version: v1
  names:
    kind: Config
    listKind: ConfigList
    plural: configs
    singular: config
  subresources:
    status: {}
