apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: openshift-image-registry-azure
  namespace: openshift-cloud-credential-operator
  annotations:
    capability.openshift.io/name: ImageRegistry+CloudCredential
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
spec:
  serviceAccountNames:
  - cluster-image-registry-operator
  - registry
  secretRef:
    name: installer-cloud-credentials
    namespace: openshift-image-registry
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: AzureProviderSpec
    permissions:
      - Microsoft.Storage/storageAccounts/blobServices/read
      - Microsoft.Storage/storageAccounts/blobServices/containers/read
      - Microsoft.Storage/storageAccounts/blobServices/containers/write
      - Microsoft.Storage/storageAccounts/blobServices/generateUserDelegationKey/action
      - Microsoft.Storage/storageAccounts/read
      - Microsoft.Storage/storageAccounts/write
      - Microsoft.Storage/storageAccounts/delete
      - Microsoft.Storage/storageAccounts/listKeys/action
      - Microsoft.Resources/tags/write
    dataPermissions:
      - Microsoft.Storage/storageAccounts/blobServices/containers/blobs/delete
      - Microsoft.Storage/storageAccounts/blobServices/containers/blobs/write
      - Microsoft.Storage/storageAccounts/blobServices/containers/blobs/read
      - Microsoft.Storage/storageAccounts/blobServices/containers/blobs/add/action
      - Microsoft.Storage/storageAccounts/blobServices/containers/blobs/move/action
