---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-image-registry-operator
  namespace: openshift-image-registry
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
