apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: image-registry-operator-alerts
  namespace: openshift-image-registry
  annotations:
    capability.openshift.io/name: ImageRegistry
    release.openshift.io/delete: "true"
    include.release.openshift.io/hypershift: "true"
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
