---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: imageregistries.imageregistry.operator.openshift.io
spec:
  group: imageregistry.operator.openshift.io
  names:
    kind: ImageRegistry
    listKind: ImageRegistryList
    plural: imageregistries
    singular: imageregistry
  scope: Namespaced
  version: v1alpha1
