---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nodecadaemon
  namespace: openshift-image-registry
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - use
  resourceNames:
  - privileged
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nodecadaemon
  namespace: openshift-image-registry
subjects:
- kind: ServiceAccount
  name: nodecadaemon
  namespace: openshift-image-registry
roleRef:
  kind: Role
  name: nodecadaemon
  apiGroup: rbac.authorization.k8s.io
